apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: external-bjs-lb
  namespace: openshift-ingress-operator
spec:
  domain: openshift.poc.bjs.com
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
