apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: register-new-ca-cert
  namespace: cp4i
spec:
  requests:
    - operands:
        - name: ibm-management-ingress-operator
      registry: common-service
      registryNamespace: ibm-common-services
